# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0139affa880e3e3b95f167c438c905c586ddd29621ffe5c53fbccd1cec7fb7c5eb01be8dc7d05d893d4c2d83cd1c14581b1b4730db0cb718b41907d0f3d34103

test:
  secret_key_base: 799188a182b17cd7f6fade587615616048a81aa107cb9aab79600c8f2eba9b775ba6fd7cf322b9221e1d575cef003c8cb38b40097bf26be9a6048fb03eb392c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
